apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: [/bin/sh, -c, 'while true; do echo $(date); sleep 1; done']
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
